"""
Catálogo estático de proyectos terminados mostrados en el portafolio.

Mantenido como lista de Python (no como modelo Django) a propósito: el contenido
es fijo, las ediciones son triviales y no hay un flujo de admin o multi-autor que
justifique una tabla en base de datos. Promover a modelo solo cuando un editor
necesite gestionar proyectos sin tocar código.
"""

PROJECTS = [
    {
        "slug": "dentalsmile",
        "title": "DentalSmile",
        "category": "Landing Page",
        "industry": "Salud · Odontología",
        "image": "mainapp/img/projects/dental.jpg",
        "html_file": "mainapp/projects/dentalsmile.html",
        "short_desc": "Landing page para clínica dental con reserva de citas, testimonios de pacientes e integración con WhatsApp.",
        "long_desc": "Una landing page de alta conversión para una clínica dental privada. Nos enfocamos en señales de confianza — reseñas reales de pacientes, certificaciones, galería antes/después — y en un flujo de reserva por WhatsApp de un solo toque que elimina la fricción de los formularios de contacto tradicionales.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "API de WhatsApp", "Google Maps"],
        "highlight_metric": "+300%",
        "highlight_label": "reservas de citas en el primer mes",
        "year": 2024,
    },
    {
        "slug": "ironforge-gym",
        "title": "IronForge Gym",
        "category": "Landing Page",
        "industry": "Fitness",
        "image": "mainapp/img/projects/gym.jpg",
        "html_file": "mainapp/projects/ironforge-gym.html",
        "short_desc": "Landing page de alta energía para gimnasio con planes de membresía, galería de entrenadores y formulario de captura de leads.",
        "long_desc": "Una landing atrevida y enfocada en conversión para un gimnasio boutique. Diseño mobile-first con CTAs fijos, tabla comparativa de membresías y un formulario de leads que llega directo al WhatsApp del dueño. Diseñada para verse tan intensa como los entrenamientos.",
        "tech_stack": ["HTML5", "Bootstrap 5", "Animaciones CSS", "JavaScript", "Formularios de Leads"],
        "highlight_metric": "2x",
        "highlight_label": "inscripciones mensuales",
        "year": 2024,
    },
    {
        "slug": "lumiere-botanica",
        "title": "Lumiere Botanica",
        "category": "E-commerce",
        "industry": "Belleza · Skincare",
        "image": "mainapp/img/projects/ecomemrce.jpg",
        "html_file": "mainapp/projects/lumiere-botanica.html",
        "short_desc": "Tienda de skincare botánico de lujo con catálogo de productos, carrito e integración de pagos con Stripe.",
        "long_desc": "Experiencia e-commerce completa para una marca premium de skincare. Catálogo de productos con categorías y filtros, carrito de compras, flujo de checkout seguro e integración con Stripe. Diseñada para sentirse lujosa desde el primer scroll.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Stripe", "Lógica de Carrito"],
        "highlight_metric": "3x",
        "highlight_label": "ventas en línea en 90 días",
        "year": 2024,
    },
    {
        "slug": "brasakfire",
        "title": "BrasakFire",
        "category": "Landing Page",
        "industry": "Restaurante · Parrilla",
        "image": "mainapp/img/projects/restaurante.jpg",
        "html_file": "mainapp/projects/brasakfire.html",
        "short_desc": "Landing page para restaurante de parrilla con menú destacado, reservas en línea e integración con Google Maps.",
        "long_desc": "Landing page irresistible para un restaurante de parrilla estilo brasileño. Menú visual, hero con historia, Google Maps embebido y un flujo de reserva en línea que entrega la solicitud al staff por WhatsApp en tiempo real.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Google Maps", "API de WhatsApp"],
        "highlight_metric": "+180%",
        "highlight_label": "reservas de fin de semana",
        "year": 2024,
    },
    {
        "slug": "structura",
        "title": "Structura Constructora",
        "category": "Corporativo",
        "industry": "Construcción",
        "image": "mainapp/img/projects/constru.jpg",
        "html_file": "mainapp/projects/structura.html",
        "short_desc": "Sitio corporativo para constructora con galería de proyectos, estadísticas y módulo de cotización.",
        "long_desc": "Sitio corporativo profesional para una constructora buscando contratos comerciales más grandes. Galería del portafolio de proyectos, contador animado de estadísticas, certificaciones, página de equipo y un formulario de cotización diseñado para capturar leads B2B serios.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Formularios de Cotización", "SEO"],
        "highlight_metric": "+5",
        "highlight_label": "contratos corporativos ganados",
        "year": 2024,
    },
    {
        "slug": "seguros-com",
        "title": "Seguros.com",
        "category": "Aplicación Web",
        "industry": "Seguros · InsurTech",
        "image": "mainapp/img/projects/soat.jpg",
        "html_file": "mainapp/projects/seguros-com.html",
        "short_desc": "Plataforma de seguros con cotizaciones al instante, comparación de coberturas y checkout en línea en minutos.",
        "long_desc": "Plataforma de comparación y compra de seguros que convierte una llamada telefónica de 30 minutos en un flujo en línea de 3 minutos. Formulario de cotización multi-paso, comparación lado a lado de coberturas y checkout integrado. Construida para conversión de leads a alto volumen.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Formularios Multi-paso", "Validación"],
        "highlight_metric": "85%",
        "highlight_label": "conversión de cotización a checkout",
        "year": 2024,
    },
    {
        "slug": "ramirez-asociados",
        "title": "Ramírez & Asociados",
        "category": "Corporativo",
        "industry": "Servicios Legales",
        "image": "mainapp/img/projects/abogado.jpg",
        "html_file": "mainapp/projects/ramirez-asociados.html",
        "short_desc": "Sitio web para firma de abogados con áreas de práctica, perfiles de los abogados y sistema de agendamiento de citas.",
        "long_desc": "Un sitio elegante y centrado en confianza para una firma de abogados corporativa. Áreas de práctica, biografías de abogados con credenciales, casos de estudio y un sistema de agendamiento de citas. Diseñado para transmitir autoridad y convertir visitantes en consultas calificadas.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Sistema de Citas", "SEO"],
        "highlight_metric": "+220%",
        "highlight_label": "consultas calificadas",
        "year": 2024,
    },
    {
        "slug": "vialidad",
        "title": "Escuela de Conducción Vialidad",
        "category": "Landing Page",
        "industry": "Educación · Capacitación",
        "image": "mainapp/img/projects/conducir.jpg",
        "html_file": "mainapp/projects/vialidad.html",
        "short_desc": "Landing page para escuela de conducción con catálogo de cursos, perfiles de instructores e inscripción en línea.",
        "long_desc": "Una landing page amigable y centrada en el estudiante para una escuela de conducción. Niveles de cursos con precios transparentes, tarjetas de instructores con insignias de experiencia, historias de éxito y un flujo de inscripción en línea sin fricción que prellenaba los mensajes de WhatsApp.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Formularios de Inscripción"],
        "highlight_metric": "+150%",
        "highlight_label": "inscripciones mensuales",
        "year": 2024,
    },
    {
        "slug": "mente-plena",
        "title": "Psicología Mente Plena",
        "category": "Landing Page",
        "industry": "Salud · Salud Mental",
        "image": "mainapp/img/projects/psicologa.jpg",
        "html_file": "mainapp/projects/mente-plena.html",
        "short_desc": "Sitio para consultorio de psicología con perfiles de terapeutas, reserva de sesiones e información de tarifas.",
        "long_desc": "Un sitio web calmado y reconfortante para un consultorio de psicología. Perfiles de terapeutas con especialidades, tipos de sesión y tarifas, FAQs que atienden las dudas más comunes y un flujo de reserva confidencial. Diseñado para hacer que un primer paso difícil se sienta fácil.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Reservas", "Privacidad"],
        "highlight_metric": "4x",
        "highlight_label": "reservas semanales de sesiones",
        "year": 2024,
    },
    {
        "slug": "bella-spa",
        "title": "Bella Spa",
        "category": "Landing Page",
        "industry": "Bienestar · Belleza",
        "image": "mainapp/img/projects/spa.jpg",
        "html_file": "mainapp/projects/bella-spa.html",
        "short_desc": "Centro de bienestar y spa de lujo con catálogo de tratamientos, reservas en línea y galería de fotos.",
        "long_desc": "Una landing page serena y con sensación premium para un spa de lujo. Catálogo de tratamientos con descripciones y precios, galería inmersiva de fotos, upsell de bonos regalo y un flujo de reservas en línea que llena citas mientras el equipo se enfoca en los huéspedes.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Galería de Imágenes", "Reservas"],
        "highlight_metric": "+240%",
        "highlight_label": "reservas en línea",
        "year": 2024,
    },
    {
        "slug": "wanderlust-travel",
        "title": "Wanderlust Travel",
        "category": "Corporativo",
        "industry": "Viajes · Turismo",
        "image": "mainapp/img/projects/viaje.jpg",
        "html_file": "mainapp/projects/wanderlust-travel.html",
        "short_desc": "Sitio web para agencia de viajes con paquetes por destino, galería de tours y sistema de reserva de viajes.",
        "long_desc": "Un sitio inspirador para una agencia de viajes construido alrededor de la narrativa y de imágenes impactantes de destinos. Paquetes de tours curados, galerías inmersivas, testimonios de viajeros y un flujo de reservas multi-paso para clientes internacionales.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Reservas Multi-paso", "Galerías"],
        "highlight_metric": "+190%",
        "highlight_label": "reservas de paquetes",
        "year": 2024,
    },
    {
        "slug": "colombia-viva",
        "title": "Colombia Viva Tours",
        "category": "Landing Page",
        "industry": "Viajes · Aventura",
        "image": "mainapp/img/projects/otro.jpg",
        "html_file": "mainapp/projects/colombia-viva.html",
        "short_desc": "Landing page de turismo de aventura con imágenes inmersivas, previews de itinerarios y formulario de cotización.",
        "long_desc": "Una landing page atrevida de turismo de aventura dirigida a viajeros internacionales visitando Colombia. Imágenes a pantalla completa, itinerarios día a día, reseñas reales de viajeros y un formulario de cotización que convierte la curiosidad en consultas calificadas en minutos.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Captura de Leads"],
        "highlight_metric": "+260%",
        "highlight_label": "consultas internacionales",
        "year": 2024,
    },
    {
        "slug": "muvit",
        "title": "MuvIt Mudanzas",
        "category": "Landing Page",
        "industry": "Logística · Mudanzas",
        "image": "mainapp/img/projects/mundaza.jpg",
        "html_file": "mainapp/projects/muvit.html",
        "short_desc": "Sitio para empresa de mudanzas y logística con planes de servicio, calculadora de cotización instantánea y galería de flota.",
        "long_desc": "Una landing page centrada en confianza para una empresa de mudanzas y logística. Tres niveles de planes de servicio, una calculadora de cotización instantánea que estima mudanzas en vivo, galería de flota e insignias de mudanza asegurada que vencen la principal objeción del sector.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Calculadora de Cotización"],
        "highlight_metric": "+170%",
        "highlight_label": "leads calificados",
        "year": 2024,
    },
    {
        "slug": "patitas-vet",
        "title": "Patitas Vet",
        "category": "Landing Page",
        "industry": "Salud · Veterinaria",
        "image": "mainapp/img/projects/veterarianria.jpg",
        "html_file": "mainapp/projects/patitas-vet.html",
        "short_desc": "Sitio para clínica veterinaria con servicios, reserva de citas, sección de peluquería canina e información de emergencias.",
        "long_desc": "Un sitio cálido y familiar para una clínica veterinaria. Resumen de servicios, reserva de citas, complementos de peluquería canina y una línea de emergencia claramente visible. Diseñado para sentirse tan acogedor como el personal dentro de la clínica.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Reserva de Citas"],
        "highlight_metric": "+200%",
        "highlight_label": "dueños nuevos que reservaron",
        "year": 2024,
    },
    {
        "slug": "devcraft",
        "title": "DevCraft Software",
        "category": "Portafolio",
        "industry": "Software · Tecnología",
        "image": "mainapp/img/projects/software.jpg",
        "html_file": "mainapp/projects/devcraft.html",
        "short_desc": "Portafolio de desarrollador con preview de código en vivo, showcase de stack y casos de estudio.",
        "long_desc": "Un sitio de portafolio enfocado en desarrolladores con diseño inspirado en terminal, previews de código en vivo, showcase animado del stack tecnológico y casos de estudio detallados. Construido para ganar contratos freelance mostrando — no contando — profundidad técnica.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Animaciones de Código"],
        "highlight_metric": "+12",
        "highlight_label": "contratos freelance en Q1",
        "year": 2024,
    },
    {
        "slug": "premium-homes",
        "title": "Premium Homes",
        "category": "Corporativo",
        "industry": "Bienes Raíces",
        "image": "mainapp/img/projects/constructura.jpg",
        "html_file": "mainapp/projects/premium-homes.html",
        "short_desc": "Sitio para constructora con listados de propiedades, tours virtuales e integración con calculadora de hipoteca.",
        "long_desc": "Un sitio web premium para una constructora de bienes raíces. Listados de propiedades con fichas detalladas, tours virtuales embebidos, una calculadora de hipoteca integrada que precalifica compradores y un formulario de leads que enruta las consultas serias directo al equipo comercial.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Calculadora de Hipoteca", "Tours"],
        "highlight_metric": "+8",
        "highlight_label": "unidades pre-vendidas desde el sitio",
        "year": 2024,
    },
    {
        "slug": "ironforge-v2",
        "title": "IronForge Gym v2",
        "category": "Landing Page",
        "industry": "Fitness",
        "image": "mainapp/img/projects/gym2.jpg",
        "html_file": "mainapp/projects/ironforge-v2.html",
        "short_desc": "Rediseño de landing page para gimnasio con imágenes a pantalla completa, horarios de clases y comparación de membresías.",
        "long_desc": "Un rediseño completo de la landing original de IronForge — imágenes a pantalla completa, horario semanal de clases, comparación lado a lado de membresías e historias de éxito de miembros. Construida alrededor de lo que realmente generó conversiones en la primera versión.",
        "tech_stack": ["HTML5", "Bootstrap 5", "JavaScript", "Horarios", "CTAs A/B"],
        "highlight_metric": "+45%",
        "highlight_label": "tasa de conversión vs v1",
        "year": 2025,
    },
]

PROJECTS_BY_SLUG = {p["slug"]: p for p in PROJECTS}
