"""
Django settings for sergio project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------
# Load .env from project root (no-op if file is missing)
# ----------------------------------------------------------------
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name: str, default: str = '') -> list[str]:
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG')

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS')

# Django respeta el esquema HTTPS pasado por el proxy
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'meta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sergio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mainapp.context_processors.site_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'sergio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = os.environ['DJANGO_LANGUAGE_CODE']

TIME_ZONE = os.environ['DJANGO_TIME_ZONE']

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ----------------------------------------------------------------
# Site identity — used in canonical URLs, sitemap, JSON-LD, OG tags.
# ----------------------------------------------------------------
SITE_ORIGIN = os.environ['SITE_ORIGIN']
SITE_NAME = os.environ['SITE_NAME']

# ----------------------------------------------------------------
# Contact channels — used in views (WhatsApp redirects) and JSON-LD.
# ----------------------------------------------------------------
WHATSAPP_NUMBER = os.environ['WHATSAPP_NUMBER']
CONTACT_EMAIL = os.environ['CONTACT_EMAIL']
CONTACT_PHONE = os.environ['CONTACT_PHONE']

# ----------------------------------------------------------------
# Social profiles — surfaced in footer links and JSON-LD `sameAs`.
# ----------------------------------------------------------------
SOCIAL_INSTAGRAM = os.environ['SOCIAL_INSTAGRAM']
SOCIAL_FACEBOOK = os.environ['SOCIAL_FACEBOOK']
SOCIAL_LINKEDIN = os.environ['SOCIAL_LINKEDIN']
SOCIAL_GITHUB = os.environ['SOCIAL_GITHUB']

# ----------------------------------------------------------------
# Google Ads / Analytics — leave empty in .env to disable a specific tag block.
# ----------------------------------------------------------------
GTM_CONTAINER_ID = os.environ['GTM_CONTAINER_ID']
GA4_MEASUREMENT_ID = os.environ['GA4_MEASUREMENT_ID']
GOOGLE_ADS_ID = os.environ['GOOGLE_ADS_ID']
GOOGLE_ADS_LEAD_LABEL = os.environ['GOOGLE_ADS_LEAD_LABEL']

# ----------------------------------------------------------------
# Meta (Facebook) Pixel + Conversions API
# Empty CAPI token disables server-side tracking but keeps the browser pixel.
# TEST_EVENT_CODE is shown ONLY in the "Test Events" tab of Meta Events Manager;
# leave empty in production.
# ----------------------------------------------------------------
META_PIXEL_ID = os.environ['META_PIXEL_ID']
META_CAPI_ACCESS_TOKEN = os.environ['META_CAPI_ACCESS_TOKEN']
META_TEST_EVENT_CODE = os.environ['META_TEST_EVENT_CODE']
